version: 2.0
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: Process Git submodules
          command:
            git submodule init && git submodule update
      - run:
          name: Restore packages
          command:
            dotnet restore
      - run:
          name: Build project
          command:
            dotnet build
      - run:
          name: Run tests
          command:
            dotnet test
